
POST {{baseUrl}}/save
content-type: application/json

{
  "name": "Tom"
}

###


POST {{baseUrl}}/save
content-type: application/json

{
  "userName": "Tom"
}

###

POST {{baseUrl}}/save
content-type: application/json

{
  "userName": "Tom",
  "password": "11"
}

###

POST {{baseUrl}}/save
content-type: application/json

{
  "userName": "Tom",
  "password": "1133344"
}

###

POST {{baseUrl}}/save
content-type: application/json

{
  "userName": "Tom",
  "password": "1133344",
  "account": "account"
}

###
