
spring:
  rabbitmq:
    # host: myserverhost
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123321
    # 消息确认配置项
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
